#include "Values.hpp"

const Building buildingIDS[178] =
{
	//{ 0x87, "Able Sisters Door",false },
	{ 0xFC, "None", false},
	{ 0xE2, "Archway Sculpture", false},
	{ 0xC4, "Balloon Arch", false},
	{ 0x6F, "Bean Day ? Face Cutout Standee", true},
	{ 0xD4, "Bell" , false},
	{ 0xA9, "Blue Bench" , false},
	{ 0x98, "Brick Bridge(N - S)" , false},
	{ 0x9A, "Brick Bridge(NW - SE)" , false},
	{ 0x99, "Brick Bridge(SW - NE)" , false},
	{ 0x9B, "Brick Bridge(W - E)" , false},
	{ 0x5B, "Bulletin Board" , false},
	{ 0xD9, "Bus Stop" , false},
	{ 0x4E, "Cafe" , false},
	{ 0x5F, "Camper's Tent" , false},
	{ 0xCA, "Camping Cot" , false},
	{ 0xC6, "Campsite" , false},
	{ 0x75, "Carp Banner ? Face Cutout Standee", true},
	{ 0xDE, "Caution Sign" , false},
	{ 0xE3, "Chair Sculpture" , false},
	{ 0x61, "Chip's Tent" , true},
	{ 0xF6, "Circle Topiary" , false},
	{ 0x4D, "Classic Police Station" , false},
	{ 0x50, "Classic Town Hall" , false},
	{ 0x54, "Classic Train Station" , false},
	{ 0x90, "Cobblestone Bridge(N - S)" , false},
	{ 0x92, "Cobblestone Bridge(NW - SE)" , false},
	{ 0x91, "Cobblestone Bridge(SW - NE)" , false},
	{ 0x93, "Cobblestone Bridge(W - E)" , false},
	{ 0x65, "Countdown Board" , true},
	{ 0xE1, "Cube Sculpture" , false},
	{ 0xDC, "Custom - Design Sign" , false},
	{ 0xDF, "Do - Not - Enter Sign" , false},
	{ 0x5D, "Dock" , false},
	// {0x80, "Dream Suite Door" , false},
	{ 0x67, "Dream World Bed" , true},
	{ 0xEA, "Drilling Rig" , false},
	{ 0x74, "Earth Day Face Cutout Standee", true},
	{ 0x71, "Empty ? " , false},
	{ 0x7D, "Explorer's Day Face Cutout Standee", true},
	{ 0xDD, "Face - Cutout Standee" , false},
	{ 0x6C, "Face Cutout Standee(6C)" , false},
	{ 0x6D, "Face Cutout Standee(6D)" , false},
	{ 0x70, "Face Cutout Standee(70)" , false},
	{ 0x73, "Face Cutout Standee(73)" , false},
	{ 0x76, "Face Cutout Standee(76)" , false},
	{ 0x78, "Face Cutout Standee(78)" , false},
	{ 0x79, "Face Cutout Standee(79)" , false},
	{ 0x7B, "Face Cutout Standee(7B)" , false},
	{ 0x7C, "Face Cutout Standee(7C)" , false},
	{ 0x7F, "Face Cutout Standee(7F)" , false},
	{ 0xAE, "Fairy - Tale Bench" , false},
	{ 0xBC, "Fairy - Tale Clock" , false},
	{ 0xC2, "Fairy - Tale Streetlight" , false},
	{ 0x52, "Fairy - tale Town Hall" , false},
	{ 0x56, "Fairy - tale Train Station" , false},
	{ 0xA4, "Fairy Tale Bridge(N - S)" , false},
	{ 0xA6, "Fairy Tale Bridge(NW - SE)" , false},
	{ 0xA5, "Fairy Tale Bridge(SW - NE)" , false},
	{ 0xA7, "Fairy Tale Bridge(W - E)" , false},
	{ 0xD8, "Fence" , false},
	{ 0xDA, "Fire Hydrant" , false},
	{ 0xC9, "Fire Pit" , false},
	{ 0xC5, "Flower Arch" , false},
	{ 0xB0, "Flower Bed" , false},
	{ 0xF9, "Flower Clock" , false},
	{ 0x77, "Flowers Face Cutout Standee", true},
	{ 0xB7, "Fountain" , false},
	{ 0x63, "Franklin's Table" , true},
	{ 0xB4, "Garbage Can" , false},
	// {0x85, "Garden Shop Door" , false},
	{ 0xCF, "Geyser" , false},
	{ 0x6E, "Groundhog Day Face Cutout Standee", true},
	{ 0xC8, "Hammock" , false},
	{ 0xCE, "Hot Spring" , false},
	{ 0xE5, "Illuminated Arch" , false},
	{ 0xE6, "Illuminated Clock" , false},
	{ 0xE4, "Illuminated Heart" , false},
	{ 0xE7, "Illuminated Tree" , false},
	{ 0xB2, "Instrument Shelter" , false},
	{ 0x5C, "Island Storage Bin" , false},
	{ 0xB9, "Jungle Gym" , false},
	{ 0x5E, "Katrina's Tent" , true},
	// {0x88, "Labelle's Door" , false},
	{ 0x7A, "Labor Day Face Cutout Standee", true},
	{ 0xEF, "Lighthouse" , false},
	{ 0x6A, "Lloid" , false},
	{ 0xAC, "Log Bench" , false},
	{ 0x04, "Mailbox Only(Player 1)" , false},
	{ 0x05, "Mailbox Only(Player 2)" , false},
	{ 0x06, "Mailbox Only(Player 3)" , false},
	{ 0x07, "Mailbox Only(Player 4)" , false},
	{ 0x8F, "Main Street Bench(facing Right)" , false},
	// {0x81, "Main Street Door ? (81)" , false},
	// {0x82, "Main Street Door ? (82)" , false},
	// {0x86, "Main Street Door ? (86)" , false},
	{ 0x8E, "Main Street Lamp" , false},
	{ 0xAB, "Metal Bench" , false},
	{ 0xF3, "Moai Statue" , false},
	{ 0xAD, "Modern Bench" , false},
	{ 0x9C, "Modern Bridge(N - S)" , false},
	{ 0x9E, "Modern Bridge(NW - SE)" , false},
	{ 0x9D, "Modern Bridge(SW - NE)" , false},
	{ 0x9F, "Modern Bridge(W - E)" , false},
	{ 0xBB, "Modern Clock" , false},
	{ 0x4C, "Modern Police Station" , false},
	{ 0xC1, "Modern Streetlight" , false},
	{ 0x53, "Modern Town Hall" , false},
	{ 0x57, "Modern Train Station" , false},
	{ 0x84, "Museum Donation Board" , false},
	{ 0x62, "Nat's Tent" , true},
	{ 0x6B, "New Years Day Face Cutout Standee", true},
	// {0x89, "Nook's Homes Door" , false},
	// {0x83, "Nookling Junction Door" , false},
	{ 0xCB, "Outdoor Chair" , false},
	{ 0xEB, "Parabolic Antenna" , false},
	{ 0xBA, "Park Clock" , false},
	{ 0x64, "Pave's Dance Stage" , true},
	//{ 0x8D, "Photo Booth" , false},
	{ 0xC7, "Picnic Blanket" , false},
	{ 0xB5, "Pile Of Pipes" , false},
	{ 0x00, "Player 1 House" , false},
	{ 0x01, "Player 2 House" , false},
	{ 0x02, "Player 3 House" , false},
	{ 0x03, "Player 4 House" , false},
	// {0x8A, "Post Office Door" , false},
	{ 0xF4, "Pyramid" , false},
	{ 0xD7, "Race Of Rice" , false},
	{ 0x5A, "Railroad Crossing Arms" , false},
	{ 0x58, "Recycle Shop" , false},
	{ 0x66, "Redd's Stand" , true},
	{ 0x60, "Redd's Tent" , true},
	{ 0x4F, "Reset Center" , false},
	{ 0xBF, "Round Streetlight" , false},
	{ 0xB3, "Sandbox" , false},
	{ 0xD6, "Scarecrow" , false},
	{ 0xEC, "Solar Panels" , false},
	{ 0xF5, "Sphinx" , false},
	{ 0xF7, "Square Topiary" , false},
	{ 0x72, "St.Patrick's Day Face Cutout Standee", true},
	{ 0xE8, "Stadium Light" , false},
	{ 0xD0, "Statue Fountain" , false},
	{ 0xD1, "Stone Tablet" , false},
	{ 0xF1, "Stonehenge" , false},
    { 0xBE, "Street Lamp" , false},
    { 0xC0, "Streetlight" , false},
	{ 0x94, "Suspension Bridge(N - S)" , false},
	{ 0x96, "Suspension Bridge(NW - SE)" , false},
	{ 0x95, "Suspension Bridge(SW - NE)" , false},
	{ 0x97, "Suspension Bridge(W - E)" , false},
	{ 0xB8, "Tire Toy" , false},
	{ 0xCC, "Torch" , false},
	{ 0xF2, "Totem Pole" , false},
	{ 0xF0, "Tower" , false},
	{ 0x59, "Town Plaza" , false},
	{ 0x7E, "Toy Day ? Face Cutout Standee", true},
	{ 0xDB, "Traffic Signal" , false},
	{ 0xF8, "Tulip Topiary" , false},
	{ 0xE9, "Video Screen" , false},
	{ 0x08, "Villager 1's House" , false},
	{ 0x09, "Villager 2's House" , false},
	{ 0x0A, "Villager 3's House" , false},
	{ 0x0B, "Villager 4's House" , false},
	{ 0x0C, "Villager 5's House" , false},
	{ 0x0D, "Villager 6's House" , false},
	{ 0x0E, "Villager 7's House" , false},
	{ 0x0F, "Villager 8's House" , false},
	{ 0x10, "Villager 9's House" , false},
	{ 0x11, "Villager 10's House" , false},
	{ 0xB1, "Water Fountain" , false},
	{ 0xD2, "Water Pump" , false},
	{ 0xB6, "Water Well" , false},
	{ 0xED, "Wind Turbine" , false},
	{ 0xEE, "Windmill" , false},
	{ 0xD3, "Wisteria Trellis" , false},
	{ 0xAA, "Wood Bench" , false},
	{ 0xA8, "Yellow Bench" , false},
	{ 0xE0, "Yield Sign" , false},
	{ 0xD5, "Zen Bell" , false},
	{ 0xAF, "Zen Bench" , false},
	{ 0xA0, "Zen Bridge(N - S)" , false},
	{ 0xA2, "Zen Bridge(NW - SE)" , false},
	{ 0xA1, "Zen Bridge(SW - NE)" , false},
	{ 0xA3, "Zen Bridge(W - E)" , false},
	{ 0xBD, "Zen Clock" , false},
	{ 0xCD, "Zen Garden" , false},
	{ 0xC3, "Zen Streetlight" , false},
	{ 0x51, "Zen Town Hall" , false},
	{ 0x55, "Zen Train Station", false}
};

const IDs rooms[95] =
{
    { 0x00, "Town" },
    { 0x01, "Main Street" },
    { 0x02, "Train Station" },
    { 0x03, "Player 1 Main Room" },
    { 0x04, "Player 1 Upstairs" },
    { 0x05, "Player 1 Basement" },
    { 0x06, "Player 1 Right Room" },
    { 0x07, "Player 1 Left Room" },
    { 0x08, "Player 1 Top Room" },
    { 0x09, "Player 2 Main Room" },
    { 0x0A, "Player 2 Upstairs" },
    { 0x0B, "Player 2 Basement" },
    { 0x0C, "Player 2 Right Room" },
    { 0x0D, "Player 2 Left Room" },
    { 0x0E, "Player 2 Top Room" },
    { 0x0F, "Player 3 Main Room" },
    { 0x10, "Player 3 Upstairs" },
    { 0x11, "Player 3 Basement" },
    { 0x12, "Player 3 Right Room" },
    { 0x13, "Player 3 Left Room" },
    { 0x14, "Player 3 Top Room" },
    { 0x15, "Player 4 Main Room" },
    { 0x16, "Player 4 Upstairs" },
    { 0x17, "Player 4 Basement" },
    { 0x18, "Player 4 Right Room" },
    { 0x19, "Player 4 Left Room" },
    { 0x1A, "Player 4 Top Room" },
    { 0x1B, "Villager 1 House" },
    { 0x1C, "Villager 2 House" },
    { 0x1D, "Villager 3 House" },
    { 0x1E, "Villager 4 House" },
    { 0x1F, "Villager 5 House" },
    { 0x20, "Villager 6 House" },
    { 0x21, "Villager 7 House" },
    { 0x22, "Villager 8 House" },
    { 0x23, "Villager 9 House" },
    { 0x24, "Villager 10 House" },
    { 0x25, "Camping Grounds" },
    { 0x26, "Town Hall" },
    { 0x2B, "Retail" },
    { 0x2C, "Nat's Tent (Bug-Off)" },
    { 0x2E, "Chip's Tent (Fishing Tourney)" },
    { 0x30, "Police Station (Copper)" },
    { 0x31, "Police Station (Booker)" },
    { 0x32, "The Roost Café" },
    { 0x34, "Reset Centre" },
    { 0x35, "Redd's Tent" },
    { 0x36, "Katrina's Tent" },
    { 0x37, "Katrina's Main Street Shop" },
    { 0x38, "Nook's Cranny" },
    { 0x39, "T&T Mart" },
    { 0x3A, "Super T&T" },
    { 0x3B, "TIY" },
    { 0x3C, "T&T Emporium - Ground Floor" },
    { 0x3D, "T&T Emporium - Floor 1" },
    { 0x3E, "GracieGracie (T&T Emporium - Floor 2)" },
    { 0x3F, "Able Sisters - Mable & Sable (Clothing)" },
    { 0x40, "Able Sisters - Labelle (Accessories)" },
    { 0x41, "Nook's Homes (House Exteriors)" },
    { 0x42, "Kick's (Shoe Shop)" },
    { 0x43, "Gardening Store (Initial)" },
    { 0x44, "Gardening Store (Joint w/ TIY)" },
    { 0x45, "Club LOL" },
    { 0x46, "Club LOL Night Disco" },
    { 0x47, "Club LOL Saturday Night (K.K. Songs)" },
    { 0x48, "Shampoodle" },
    { 0x49, "Museum - Ground Floor" },
    { 0x4A, "Fish Gallery - Main Room" },
    { 0x4B, "Fish Gallery - North West Room" },
    { 0x4C, "Fish Gallery - North East Room" },
    { 0x4D, "Bug Gallery - Main Room" },
    { 0x4E, "Bug Gallery - North East Room" },
    { 0x4F, "Bug Gallery - North West Room" },
    { 0x50, "Fossil Gallery - Main Room" },
    { 0x51, "Fossil Gallery - South Room" },
    { 0x52, "Fossil Gallery - North West Room" },
    { 0x53, "Art Gallery - Main Room" },
    { 0x54, "Art Gallery - East Room" },
    { 0x55, "Museum - 1st Floor (Shop)" },
    { 0x56, "Museum Exhibit - North West" },
    { 0x57, "Museum Exhibit - South West" },
    { 0x58, "Museum Exhibit - North East" },
    { 0x59, "Museum Exhibit - South East" },
    { 0x5A, "Post Office" },
    { 0x5B, "Dream Suite" },
    { 0x5C, "Photo Booth" },
    { 0x63, "Isabelle Spotlight/ Load Town Area" },
    { 0x67, "Island Shack" },
    { 0x68, "Island" },
    { 0x9F, "Campground - West" },
    { 0xA0, "Campground - East" },
    { 0xA1, "Special Character RV" },
    { 0xA2, "Villager RV" },
    { 0xA3, "Move Furniture Like AC:HHD Tutorial (w/ Lottie)" },
    { 0xA4, "Amiibo Camera" }
};

const IDs regions[15] =
{
    { 0xFF, "Default Country" },
    { 49, "USA" },
    { 110, "UK" },
    { 1, "Japan" },
    { 136, "South Korea" },
    { 65, "Australia" },
    { 18, "Canada" },
    { 77, "France" },
    { 78, "Germany" },
    { 105, "Spain" },
    { 83, "Italy" },
    { 82, "Ireland" },
    { 120, "Djibouti" },
    { 186, "Bermuda" },
    { 82, "Jordan" }
};

