#include "Values.hpp"

const IDs buildingIDS[189] =
{
    { 0x00,   "Player 1 House" },
    { 0x01,   "Player 2 House" },
    { 0x02,   "Player 3 House" },
    { 0x03,   "Player 4 House" },
    { 0x04,   "Mailbox Only(Player 1)" },
    { 0x05,   "Mailbox Only(Player 2)" },
    { 0x06,   "Mailbox Only(Player 3)" },
    { 0x07,   "Mailbox Only(Player 4)" },
    { 0x08,   "Villager 1" },
    { 0x09,   "Villager 2" },
    { 0x0A,   "Villager 3" },
    { 0x0B,   "Villager 4" },
    { 0x0C,   "Villager 5" },
    { 0x0D,   "Villager 6" },
    { 0x0E,   "Villager 7" },
    { 0x0F,   "Villager 8" },
    { 0x10,   "Villager 9" },
    { 0x11,   "Villager 10" },
    { 0x4C,	"Modern Police Station" },
    { 0x4D,	"Classic Police Station" },
    { 0x4E,	"Cafe" },
    { 0x4F,	"Reset Center" },
    { 0x50,   "Classic Town Hall" },
    { 0x51,   "Zen Town Hall" },
    { 0x52,   "Fairy - tale Town Hall" },
    { 0x53,   "Modern Town Hall" },
    { 0x54,   "Classic Train Station" },
    { 0x55,   "Zen Train Station" },
    { 0x56,   "Fairy - tale Train Station" },
    { 0x57,   "Modern Train Station" },
    { 0x58,   "Recycle Shop" },
    { 0x59,   "Town Plaza" },
    { 0x5A,   "Railroad Crossing Arms" },
    { 0x5B,   "Bulletin Board" },
    { 0x5C,   "Island Storage Bin" },
    { 0x5D,   "Dock" },
    { 0x5E,   "Katrina's Tent" },
    { 0x5F,   "Camper's Tent" },
    { 0x60,   "Redd's Tent" },
    { 0x61,   "Chip's Tent" },
    { 0x62,   "Nat's Tent" },
    { 0x63,   "Franklin's Table" },
    { 0x64,   "Pave's Dance Stage" },
    { 0x65,   "Countdown Board" },
    { 0x66,   "Redd's Stand" },
    { 0x67,   "Dream World Bed" },
    { 0x6A,   "Lloid" },
    { 0x6B,   "New Years Day Face Cutout Standee" },
    { 0x6C,   "Face Cutout Standee(6C)" },
    { 0x6D,   "Face Cutout Standee(6D)" },
    { 0x6E,   "Groundhog Day Face Cutout Standee" },
    { 0x6F,   "Bean Day ? Face Cutout Standee" },
    { 0x70,   "Face Cutout Standee(70)" },
    { 0x71,   "Empty ? " },
    { 0x72,   "St.Patrick's Day Face Cutout Standee" },
    { 0x73,   "Face Cutout Standee(73)" },
    { 0x74,   "Earth Day Face Cutout Standee" },
    { 0x75,   "Carp Banner ? Face Cutout Standee" },
    { 0x76,   "Face Cutout Standee(76)" },
    { 0x77,   "Flowers Face Cutout Standee" },
    { 0x78,   "Face Cutout Standee(78)" },
    { 0x79,   "Face Cutout Standee(79)" },
    { 0x7A,   "Labor Day Face Cutout Standee" },
    { 0x7B,   "Face Cutout Standee(7B)" },
    { 0x7C,   "Face Cutout Standee(7C)" },
    { 0x7D,   "Explorer's Day Face Cutout Standee" },
    { 0x7E,   "Toy Day ? Face Cutout Standee" },
    { 0x7F,   "Face Cutout Standee(7F)" },
    { 0x80,   "Dream Suite Door" },
    { 0x81,   "Main Street Door ? (81)" },
    { 0x82,   "Main Street Door ? (82)" },
    { 0x83,   "Nookling Junction Door" },
    { 0x84,   "Museum Donation Board" },
    { 0x85,   "Garden Shop Door" },
    { 0x86,   "Main Street Door ? (86)" },
    { 0x87,   "Able Sisters Door" },
    { 0x88,   "Labelle's Door" },
    { 0x89,   "Nook's Homes Door" },
    { 0x8A,   "Post Office Door" },
    { 0x8D,   "Photo Booth" },
    { 0x8E,   "Main Street Lamp" },
    { 0x8F,   "Main Street Bench(facing Right)" },
    { 0x90,   "Cobblestone Bridge(N - S)" },
    { 0x91,   "Cobblestone Bridge(SW - NE)" },
    { 0x92,   "Cobblestone Bridge(NW - SE)" },
    { 0x93,   "Cobblestone Bridge(W - E)" },
    { 0x94,   "Suspension Bridge(N - S)" },
    { 0x95,   "Suspension Bridge(SW - NE)" },
    { 0x96,   "Suspension Bridge(NW - SE)" },
    { 0x97,   "Suspension Bridge(W - E)" },
    { 0x98,   "Brick Bridge(N - S)" },
    { 0x99,   "Brick Bridge(SW - NE)" },
    { 0x9A,   "Brick Bridge(NW - SE)" },
    { 0x9B,   "Brick Bridge(W - E)" },
    { 0x9C,   "Modern Bridge(N - S)" },
    { 0x9D,   "Modern Bridge(SW - NE)" },
    { 0x9E,   "Modern Bridge(NW - SE)" },
    { 0x9F,   "Modern Bridge(W - E)" },
    { 0xA0,   "Zen Bridge(N - S)" },
    { 0xA1,   "Zen Bridge(SW - NE)" },
    { 0xA2,   "Zen Bridge(NW - SE)" },
    { 0xA3,   "Zen Bridge(W - E)" },
    { 0xA4,   "Fairy Tale Bridge(N - S)" },
    { 0xA5,   "Fairy Tale Bridge(SW - NE)" },
    { 0xA6,   "Fairy Tale Bridge(NW - SE)" },
    { 0xA7,   "Fairy Tale Bridge(W - E)" },
    { 0xA8,   "Yellow Bench" },
    { 0xA9,   "Blue Bench" },
    { 0xAA,   "Wood Bench" },
    { 0xAB,   "Metal Bench" },
    { 0xAC,   "Log Bench" },
    { 0xAD,   "Modern Bench" },
    { 0xAE,   "Fairy - Tale Bench" },
    { 0xAF,   "Zen Bench" },
    { 0xB0,   "Flower Bed" },
    { 0xB1,   "Water Fountain" },
    { 0xB2,   "Instrument Shelter" },
    { 0xB3,   "Sandbox" },
    { 0xB4,   "Garbage Can" },
    { 0xB5,   "Pile Of Pipes" },
    { 0xB6,   "Water Well" },
    { 0xB7,   "Fountain" },
    { 0xB8,   "Tire Toy" },
    { 0xB9,   "Jungle Gym" },
    { 0xBA,   "Park Clock" },
    { 0xBB,   "Modern Clock" },
    { 0xBC,   "Fairy - Tale Clock" },
    { 0xBD,   "Zen Clock" },
    { 0xBE,   "Street Lamp" },
    { 0xBF,   "Round Streetlight" },
    { 0xC0,   "Streetlight" },
    { 0xC1,   "Modern Streetlight" },
    { 0xC2,   "Fairy - Tale Streetlight" },
    { 0xC3,   "Zen Streetlight" },
    { 0xC4,   "Balloon Arch" },
    { 0xC5,   "Flower Arch" },
    { 0xC6,   "Campsite" },
    { 0xC7,   "Picnic Blanket" },
    { 0xC8,   "Hammock" },
    { 0xC9,   "Fire Pit" },
    { 0xCA,   "Camping Cot" },
    { 0xCB,   "Outdoor Chair" },
    { 0xCC,   "Torch" },
    { 0xCD,   "Zen Garden" },
    { 0xCE,   "Hot Spring" },
    { 0xCF,   "Geyser" },
    { 0xD0,   "Statue Fountain" },
    { 0xD1,   "Stone Tablet" },
    { 0xD2,   "Water Pump" },
    { 0xD3,   "Wisteria Trellis" },
    { 0xD4,   "Bell" },
    { 0xD5,   "Zen Bell" },
    { 0xD6,   "Scarecrow" },
    { 0xD7,   "Race Of Rice" },
    { 0xD8,   "Fence" },
    { 0xD9,   "Bus Stop" },
    { 0xDA,   "Fire Hydrant" },
    { 0xDB,   "Traffic Signal" },
    { 0xDC,   "Custom - Design Sign" },
    { 0xDD,   "Face - Cutout Standee" },
    { 0xDE,   "Caution Sign" },
    { 0xDF,   "Do - Not - Enter Sign" },
    { 0xE0,   "Yield Sign" },
    { 0xE1,   "Cube Sculpture" },
    { 0xE2,   "Archway Sculpture" },
    { 0xE3,   "Chair Sculpture" },
    { 0xE4,   "Illuminated Heart" },
    { 0xE5,   "Illuminated Arch" },
    { 0xE6,   "Illuminated Clock" },
    { 0xE7,   "Illuminated Tree" },
    { 0xE8,   "Stadium Light" },
    { 0xE9,   "Video Screen" },
    { 0xEA,   "Drilling Rig" },
    { 0xEB,   "Parabolic Antenna" },
    { 0xEC,   "Solar Panels" },
    { 0xED,   "Wind Turbine" },
    { 0xEE,   "Windmill" },
    { 0xEF,   "Lighthouse" },
    { 0xF0,   "Tower" },
    { 0xF1,   "Stonehenge" },
    { 0xF2,   "Totem Pole" },
    { 0xF3,   "Moai Statue" },
    { 0xF4,   "Pyramid" },
    { 0xF5,   "Sphinx" },
    { 0xF6,   "Circle Topiary" },
    { 0xF7,   "Square Topiary" },
    { 0xF8,   "Tulip Topiary" },
    { 0xF9,   "Flower Clock" },
    { 0xFC,   "None" }
};

const IDs rooms[129] =
{
    { 0x00, "Town" },
    { 0x01, "Main Street" },
    { 0x02, "Train Station" },
    { 0x03, "Player 1 Main Room" },
    { 0x04, "Player 1 Upstairs" },
    { 0x05, "Player 1 Basement" },
    { 0x06, "Player 1 Right Room" },
    { 0x07, "Player 1 Left Room" },
    { 0x08, "Player 1 Top Room" },
    { 0x09, "Player 2 Main Room" },
    { 0x0A, "Player 2 Upstairs" },
    { 0x0B, "Player 2 Basement" },
    { 0x0C, "Player 2 Right Room" },
    { 0x0D, "Player 2 Left Room" },
    { 0x0E, "Player 2 Top Room" },
    { 0x0F, "Player 3 Main Room" },
    { 0x10, "Player 3 Upstairs" },
    { 0x11, "Player 3 Basement" },
    { 0x12, "Player 3 Right Room" },
    { 0x13, "Player 3 Left Room" },
    { 0x14, "Player 3 Top Room" },
    { 0x15, "Player 4 Main Room" },
    { 0x16, "Player 4 Upstairs" },
    { 0x17, "Player 4 Basement" },
    { 0x18, "Player 4 Right Room" },
    { 0x19, "Player 4 Left Room" },
    { 0x1A, "Player 4 Top Room" },
    { 0x1B, "Villager 1 House" },
    { 0x1C, "Villager 2 House" },
    { 0x1D, "Villager 3 House" },
    { 0x1E, "Villager 4 House" },
    { 0x1F, "Villager 5 House" },
    { 0x20, "Villager 6 House" },
    { 0x21, "Villager 7 House" },
    { 0x22, "Villager 8 House" },
    { 0x23, "Villager 9 House" },
    { 0x24, "Villager 10 House" },
    { 0x25, "Camping Grounds" },
    { 0x26, "Town Hall" },
    { 0x27, "Arriving in town via train" },
    { 0x28, "Leaving a town via train" },
    { 0x29, "Arriving in your town from another town via train" },
    { 0x2A, "First time arriving from the train (start of game)" },
    { 0x2B, "Retail" },
    { 0x2C, "Nat's Tent (Bug-Off)" },
    { 0x2D, "Bug-Off Ceremony" },
    { 0x2E, "Chip's Tent (Fishing Tourney)" },
    { 0x2F, "Fishing Tourney Ceremony" },
    { 0x30, "Police Station (Copper)" },
    { 0x31, "Police Station (Booker)" },
    { 0x32, "The Roost Café" },
    { 0x33, "Working In The Roost Café" },
    { 0x34, "Reset Centre" },
    { 0x35, "Redd's Tent" },
    { 0x36, "Katrina's Tent" },
    { 0x37, "Katrina's Main Street Shop" },
    { 0x38, "Nook's Cranny" },
    { 0x39, "T&T Mart" },
    { 0x3A, "Super T&T" },
    { 0x3B, "TIY" },
    { 0x3C, "T&T Emporium - Ground Floor" },
    { 0x3D, "T&T Emporium - Floor 1" },
    { 0x3E, "GracieGracie (T&T Emporium - Floor 2)" },
    { 0x3F, "Able Sisters - Mable & Sable (Clothing)" },
    { 0x40, "Able Sisters - Labelle (Accessories)" },
    { 0x41, "Nook's Homes (House Exteriors)" },
    { 0x42, "Kick's (Shoe Shop)" },
    { 0x43, "Gardening Store (Initial)" },
    { 0x44, "Gardening Store (Joint w/ TIY)" },
    { 0x45, "Club LOL" },
    { 0x46, "Club LOL Night Disco" },
    { 0x47, "Club LOL Saturday Night (K.K. Songs)" },
    { 0x48, "Shampoodle" },
    { 0x49, "Museum - Ground Floor" },
    { 0x4A, "Fish Gallery - Main Room" },
    { 0x4B, "Fish Gallery - North West Room" },
    { 0x4C, "Fish Gallery - North East Room" },
    { 0x4D, "Bug Gallery - Main Room" },
    { 0x4E, "Bug Gallery - North East Room" },
    { 0x4F, "Bug Gallery - North West Room" },
    { 0x50, "Fossil Gallery - Main Room" },
    { 0x51, "Fossil Gallery - South Room" },
    { 0x52, "Fossil Gallery - North West Room" },
    { 0x53, "Art Gallery - Main Room" },
    { 0x54, "Art Gallery - East Room" },
    { 0x55, "Museum - 1st Floor (Shop)" },
    { 0x56, "Museum Exhibit - North West" },
    { 0x57, "Museum Exhibit - South West" },
    { 0x58, "Museum Exhibit - North East" },
    { 0x59, "Museum Exhibit - South East" },
    { 0x5A, "Post Office" },
    { 0x5B, "Dream Suite" },
    { 0x5C, "Photo Booth" },
    { 0x5D, "Game's Initial Setup Train Ride" },
    { 0x5E, "Title Screen" },
    { 0x5F, "First time arriving into the train station (start of game)" },
    { 0x60, "Saving Screen" },
    { 0x61, "After Save & Quit (Black Screen -> Title Screen)" },
    { 0x62, "Black Screen" },
    { 0x63, "Isabelle Spotlight/ Load Town Area" },
    { 0x64, "Coming Back From A Dream (Dream Suite Bed)" },
    { 0x65, "On Kappn's Boat Going To The Island" },
    { 0x66, "On Kappn's Boat Leaving The Island" },
    { 0x67, "Island Shack" },
    { 0x68, "Island" },
    { 0x69, "Tour - Hide n' Seek" },
    { 0x6A, "Tour - Hide n' Seek - (Results)" },
    { 0x6B, "Tour - Flower Picking" },
    { 0x6C, "Tour - Flower Picking (Results)" },
    { 0x6D, "Island Tour - Fishing" },
    { 0x6E, "Island Tour - Fishing (Results)" },
    { 0x6F, "Tour - Bug Catching" },
    { 0x70, "Tour - Bug Catching (Results)" },
    { 0x71, "Tour - Balloon Popping" },
    { 0x72, "Tour - Balloon Popping (Results)" },
    { 0x77, "Island Tour - Labyrinth" },
    { 0x78, "Island Tour - Labyrinth - End Results" },
    { 0x99, "Move town to AC:WA version of game" },
    { 0x9A, "Isabelle on stage, talking about AC : HHD in ACNL" },
    { 0x9B, "Isabelle on train, introduction to WA features" },
    { 0x9C, "Player select for Isabelle on train (9C -> 9B)" },
    { 0x9D, "Desert Island Escape Minigame (Wii U)" },
    { 0x9E, "Puzzle League Minigame" },
    { 0x9F, "Campground - West" },
    { 0xA0, "Campground - East" },
    { 0xA1, "Special Character RV" },
    { 0xA2, "Villager RV" },
    { 0xA3, "Move Furniture Like AC:HHD Tutorial (w/ Lottie)" },
    { 0xA4, "Amiibo Camera" }
};

const IDs regions[15] =
{
    { 0xFF, "Default Country" },
    { 49, "USA" },
    { 110, "UK" },
    { 1, "Japan" },
    { 136, "South Korea" },
    { 65, "Australia" },
    { 18, "Canada" },
    { 77, "France" },
    { 78, "Germany" },
    { 105, "Spain" },
    { 83, "Italy" },
    { 82, "Ireland" },
    { 120, "Djibouti" },
    { 186, "Bermuda" },
    { 82, "Jordan" }
};

