#ifndef VALUES_HPP
#define VALUES_HPP

struct Buildings
{
    u8 id;
    std::string Name;
};

const std::vector<Buildings> buildingIDS =
{
    { 0x00,   "Player 1 House" },
    { 0x01,   "Player 2 House" },
    { 0x02,   "Player 3 House" },
    { 0x03,   "Player 4 House" },
    { 0x04,   "Mailbox Only(Player 1)" },
    { 0x05,   "Mailbox Only(Player 2)" },
    { 0x06,   "Mailbox Only(Player 3)" },
    { 0x07,   "Mailbox Only(Player 4)" },
    { 0x08,   "Villager 1" },
    { 0x09,   "Villager 2" },
    { 0x0A,   "Villager 3" },
    { 0x0B,   "Villager 4" },
    { 0x0C,   "Villager 5" },
    { 0x0D,   "Villager 6" },
    { 0x0E,   "Villager 7" },
    { 0x0F,   "Villager 8" },
    { 0x10,   "Villager 9" },
    { 0x11,   "Villager 10" },
    { 0x4C,	"Modern Police Station" },
    { 0x4D,	"Classic Police Station" },
    { 0x4E,	"Cafe" },
    { 0x4F,	"Reset Center" },
    { 0x50,   "Classic Town Hall" },
    { 0x51,   "Zen Town Hall" },
    { 0x52,   "Fairy - tale Town Hall" },
    { 0x53,   "Modern Town Hall" },
    { 0x54,   "Classic Train Station" },
    { 0x55,   "Zen Train Station" },
    { 0x56,   "Fairy - tale Train Station" },
    { 0x57,   "Modern Train Station" },
    { 0x58,   "Recycle Shop" },
    { 0x59,   "Town Plaza" },
    { 0x5A,   "Railroad Crossing Arms" },
    { 0x5B,   "Bulletin Board" },
    { 0x5C,   "Island Storage Bin" },
    { 0x5D,   "Dock" },
    { 0x5E,   "Katrina's Tent" },
    { 0x5F,   "Camper's Tent" },
    { 0x60,   "Redd's Tent" },
    { 0x61,   "Chip's Tent" },
    { 0x62,   "Nat's Tent" },
    { 0x63,   "Franklin's Table" },
    { 0x64,   "Pave's Dance Stage" },
    { 0x65,   "Countdown Board" },
    { 0x66,   "Redd's Stand" },
    { 0x67,   "Dream World Bed" },
    { 0x6A,   "Lloid" },
    { 0x6B,   "New Years Day Face Cutout Standee" },
    { 0x6C,   "Face Cutout Standee(6C)" },
    { 0x6D,   "Face Cutout Standee(6D)" },
    { 0x6E,   "Groundhog Day Face Cutout Standee" },
    { 0x6F,   "Bean Day ? Face Cutout Standee" },
    { 0x70,   "Face Cutout Standee(70)" },
    { 0x71,   "Empty ? " },
    { 0x72,   "St.Patrick's Day Face Cutout Standee" },
    { 0x73,   "Face Cutout Standee(73)" },
    { 0x74,   "Earth Day Face Cutout Standee" },
    { 0x75,   "Carp Banner ? Face Cutout Standee" },
    { 0x76,   "Face Cutout Standee(76)" },
    { 0x77,   "Flowers Face Cutout Standee" },
    { 0x78,   "Face Cutout Standee(78)" },
    { 0x79,   "Face Cutout Standee(79)" },
    { 0x7A,   "Labor Day Face Cutout Standee" },
    { 0x7B,   "Face Cutout Standee(7B)" },
    { 0x7C,   "Face Cutout Standee(7C)" },
    { 0x7D,   "Explorer's Day Face Cutout Standee" },
    { 0x7E,   "Toy Day ? Face Cutout Standee" },
    { 0x7F,   "Face Cutout Standee(7F)" },
    { 0x80,   "Dream Suite Door" },
    { 0x81,   "Main Street Door ? (81)" },
    { 0x82,   "Main Street Door ? (82)" },
    { 0x83,   "Nookling Junction Door" },
    { 0x84,   "Museum Donation Board" },
    { 0x85,   "Garden Shop Door" },
    { 0x86,   "Main Street Door ? (86)" },
    { 0x87,   "Able Sisters Door" },
    { 0x88,   "Labelle's Door" },
    { 0x89,   "Nook's Homes Door" },
    { 0x8A,   "Post Office Door" },
    { 0x8D,   "Photo Booth" },
    { 0x8E,   "Main Street Lamp" },
    { 0x8F,   "Main Street Bench(facing Right)" },
    { 0x90,   "Cobblestone Bridge(N - S)" },
    { 0x91,   "Cobblestone Bridge(SW - NE)" },
    { 0x92,   "Cobblestone Bridge(NW - SE)" },
    { 0x93,   "Cobblestone Bridge(W - E)" },
    { 0x94,   "Suspension Bridge(N - S)" },
    { 0x95,   "Suspension Bridge(SW - NE)" },
    { 0x96,   "Suspension Bridge(NW - SE)" },
    { 0x97,   "Suspension Bridge(W - E)" },
    { 0x98,   "Brick Bridge(N - S)" },
    { 0x99,   "Brick Bridge(SW - NE)" },
    { 0x9A,   "Brick Bridge(NW - SE)" },
    { 0x9B,   "Brick Bridge(W - E)" },
    { 0x9C,   "Modern Bridge(N - S)" },
    { 0x9D,   "Modern Bridge(SW - NE)" },
    { 0x9E,   "Modern Bridge(NW - SE)" },
    { 0x9F,   "Modern Bridge(W - E)" },
    { 0xA0,   "Zen Bridge(N - S)" },
    { 0xA1,   "Zen Bridge(SW - NE)" },
    { 0xA2,   "Zen Bridge(NW - SE)" },
    { 0xA3,   "Zen Bridge(W - E)" },
    { 0xA4,   "Fairy Tale Bridge(N - S)" },
    { 0xA5,   "Fairy Tale Bridge(SW - NE)" },
    { 0xA6,   "Fairy Tale Bridge(NW - SE)" },
    { 0xA7,   "Fairy Tale Bridge(W - E)" },
    { 0xA8,   "Yellow Bench" },
    { 0xA9,   "Blue Bench" },
    { 0xAA,   "Wood Bench" },
    { 0xAB,   "Metal Bench" },
    { 0xAC,   "Log Bench" },
    { 0xAD,   "Modern Bench" },
    { 0xAE,   "Fairy - Tale Bench" },
    { 0xAF,   "Zen Bench" },
    { 0xB0,   "Flower Bed" },
    { 0xB1,   "Water Fountain" },
    { 0xB2,   "Instrument Shelter" },
    { 0xB3,   "Sandbox" },
    { 0xB4,   "Garbage Can" },
    { 0xB5,   "Pile Of Pipes" },
    { 0xB6,   "Water Well" },
    { 0xB7,   "Fountain" },
    { 0xB8,   "Tire Toy" },
    { 0xB9,   "Jungle Gym" },
    { 0xBA,   "Park Clock" },
    { 0xBB,   "Modern Clock" },
    { 0xBC,   "Fairy - Tale Clock" },
    { 0xBD,   "Zen Clock" },
    { 0xBE,   "Street Lamp" },
    { 0xBF,   "Round Streetlight" },
    { 0xC0,   "Streetlight" },
    { 0xC1,   "Modern Streetlight" },
    { 0xC2,   "Fairy - Tale Streetlight" },
    { 0xC3,   "Zen Streetlight" },
    { 0xC4,   "Balloon Arch" },
    { 0xC5,   "Flower Arch" },
    { 0xC6,   "Campsite" },
    { 0xC7,   "Picnic Blanket" },
    { 0xC8,   "Hammock" },
    { 0xC9,   "Fire Pit" },
    { 0xCA,   "Camping Cot" },
    { 0xCB,   "Outdoor Chair" },
    { 0xCC,   "Torch" },
    { 0xCD,   "Zen Garden" },
    { 0xCE,   "Hot Spring" },
    { 0xCF,   "Geyser" },
    { 0xD0,   "Statue Fountain" },
    { 0xD1,   "Stone Tablet" },
    { 0xD2,   "Water Pump" },
    { 0xD3,   "Wisteria Trellis" },
    { 0xD4,   "Bell" },
    { 0xD5,   "Zen Bell" },
    { 0xD6,   "Scarecrow" },
    { 0xD7,   "Race Of Rice" },
    { 0xD8,   "Fence" },
    { 0xD9,   "Bus Stop" },
    { 0xDA,   "Fire Hydrant" },
    { 0xDB,   "Traffic Signal" },
    { 0xDC,   "Custom - Design Sign" },
    { 0xDD,   "Face - Cutout Standee" },
    { 0xDE,   "Caution Sign" },
    { 0xDF,   "Do - Not - Enter Sign" },
    { 0xE0,   "Yield Sign" },
    { 0xE1,   "Cube Sculpture" },
    { 0xE2,   "Archway Sculpture" },
    { 0xE3,   "Chair Sculpture" },
    { 0xE4,   "Illuminated Heart" },
    { 0xE5,   "Illuminated Arch" },
    { 0xE6,   "Illuminated Clock" },
    { 0xE7,   "Illuminated Tree" },
    { 0xE8,   "Stadium Light" },
    { 0xE9,   "Video Screen" },
    { 0xEA,   "Drilling Rig" },
    { 0xEB,   "Parabolic Antenna" },
    { 0xEC,   "Solar Panels" },
    { 0xED,   "Wind Turbine" },
    { 0xEE,   "Windmill" },
    { 0xEF,   "Lighthouse" },
    { 0xF0,   "Tower" },
    { 0xF1,   "Stonehenge" },
    { 0xF2,   "Totem Pole" },
    { 0xF3,   "Moai Statue" },
    { 0xF4,   "Pyramid" },
    { 0xF5,   "Sphinx" },
    { 0xF6,   "Circle Topiary" },
    { 0xF7,   "Square Topiary" },
    { 0xF8,   "Tulip Topiary" },
    { 0xF9,   "Flower Clock" },
    { 0xFC,   "None" }
};



/*
** Values
*/

#define     EUR_DIFFERENCE                      0x28380
#define     JAP_DIFFERENCE                      0x22A80

#define     ITEM_BYTES                          0x04
#define     RANGE_TOWN_ITEMS                    0x5000

#endif
